#!/bin/bash
source "$(dirname "$0")/options.sh"
cd "${HOME}${BDSDIR}"

perl autoresponse_ftp receive

perl fix_charsets
perl update_autoresponse >>${HOME}${LOGDIR}autoresponse.log 2>>${HOME}${LOGDIR}autoresponse.err

